; (function () {
    window.__json = true;
    window.startupInfo =
        ({ "__type": "Pageflakes.ObjectModel.PageflakeInfo, PageFlakes.ObjectModel"
        ,"VersionSuffix": "217en"
        ,"Language": "en"
        ,"DomainID": 1
        ,"LanguageID": 1
        ,"UserPublishURL": "http://www.pageflakes.com/franckMdeRomans"
        ,"UserUniqueName": "franckMdeRomans"
        ,"UserFullName": "Franck"
        , "UserGUID": "ce17f62b-b77e-4cae-a791-d40afd8ddafa"
        ,"UserVersionNo": 354
        ,"CurrentPageID": 33874442
        ,"CurrentPageVersionNo": 9
        ,"IsSubscribedForNewsletter": false
        ,"ViewingPageOf": "franckMdeRomans"
        ,"Template": { "__type": "Pageflakes.ObjectModel.Template, PageFlakes.ObjectModel"
            ,"ModuleHtml": "\u003cdiv class=\"flake_placeholder\"\u003e \u003cdiv class=\"flake\"\u003e \u003cdiv class=\"flake_header\" onmouseover=\"opqTb(this)\" onmouseout=\"alphaTb(this)\" id=\"handle_FLAKE_ID_\"\u003e \u003cdiv class=\"flake_toolbar\"\u003e \u003ca class=\"refresh_icon\" style=\"display:none;\" title=\"Refresh Flake\" id=\"refresh_FLAKE_ID_\" onmouseover=\"hover(this)\" onmouseout=\"hout(this)\" onclick=\"$module(\u0027_FLAKE_ID_\u0027).refresh()\"\u003eRefresh\u003c/a\u003e \u003ca class=\"sendFlake_icon\" id=\"sendFlake_FLAKE_ID_\" onmouseover=\"hover(this)\" onmouseout=\"hout(this)\" onmousedown=\"$stopBubble(event)\" onclick=\"$module(\u0027_FLAKE_ID_\u0027).showFlakeMenu()\"\u003eSend\u003c/a\u003e \u003ca class=\"settings_icon\" id=\"editLink_FLAKE_ID_\" title=\"Edit Flake settings\" onmouseover=\"hover(this)\" onmouseout=\"hout(this)\" onmousedown=\"$stopBubble(event)\" onclick=\"$module(\u0027_FLAKE_ID_\u0027).toggleEdit()\"\u003eEDIT\u003c/a\u003e \u003ca class=\"close_icon\" id=\"closeLink_FLAKE_ID_\" title=\"Remove Flake\" onmouseover=\"hover(this)\" onmousedown=\"$stopBubble(event)\" onmouseout=\"hout(this)\" onclick=\"$module(\u0027_FLAKE_ID_\u0027).close()\" \u003ex\u003c/a\u003e \u003c/div\u003e \u003cdiv class=\"flake_title\"\u003e \u003cdiv class=\"flake_icon\"\u003e\u003cimg OnError=\u0027$module(\"_FLAKE_ID_\").loadDefaultFavicon(\"icon_FLAKE_ID_\");\u0027 id=\"icon_FLAKE_ID_\" /\u003e\u003c/div\u003e \u003cdiv class=\"flake_name_container\"\u003e \u003cspan class=\"flake_name\" id=\"title_FLAKE_ID_\"\u003e_FLAKE_TITLE_\u003c/span\u003e \u003cspan class=\"rss_number\" id=\"number_FLAKE_ID_\"\u003e\u003c/span\u003e \u003c/div\u003e \u003c/div\u003e \u003c/div\u003e \u003cdiv id=\"editContainer_FLAKE_ID_\" style=\"display:none\" \u003e \u003ctable class=\"flake_tabbar\" cellspacing=\"0\" cellpadding=\"0\"\u003e \u003ctr\u003e \u003ctd width=\"100\" id=\"td_tab_basic_FLAKE_ID_\"\u003e\u003cdiv id=\"tab_basic_FLAKE_ID_\" class=\"edit_tabup\" onclick=\"$module(\u0027_FLAKE_ID_\u0027).showBasicSetting()\" disable=\"$remove(\u0027td_tab_basic_FLAKE_ID_\u0027)\" \u003eSettings\u003c/div\u003e\u003c/td\u003e \u003ctd width=\"100\" id=\"td_tab_other_FLAKE_ID_\"\u003e\u003cdiv id=\"tab_other_FLAKE_ID_\" class=\"edit_tabdown\" onclick=\"$module(\u0027_FLAKE_ID_\u0027).showAdvancedSetting()\" disable=\"$remove(\u0027td_tab_other_FLAKE_ID_\u0027)\" \u003ePreferences\u003c/div\u003e\u003c/td\u003e \u003ctd \u003e&nbsp;\u003c/td\u003e \u003c/tr\u003e \u003c/table\u003e \u003cdiv class=\"flake_settings\" \u003e \u003cdiv id=\"editBody_FLAKE_ID_\" style=\"padding:8px\"\u003e\u003c/div\u003e \u003cdiv id=\"editOthers_FLAKE_ID_\" style=\"padding:8px;display:none; height:100px\"\u003e \u003ctable width=100%\u003e \u003ctr\u003e\u003ctd width=70\u003eFlake title:\u003c/td\u003e\u003ctd\u003e\u003cinput style=\"width:70%\" type=\"text\" id=\"flakeTitleEdit_FLAKE_ID_\" onkeypress=\"if(event.keyCode==13)$module(\u0027_FLAKE_ID_\u0027).editEdit();\" value=\"_FLAKE_TITLE_\"/\u003e\u003c/td\u003e\u003c/tr\u003e \u003ctr\u003e\u003ctd\u003e&nbsp;\u003c/td\u003e\u003ctd\u003e\u003cinput type=\"button\" value=\"Save\" onclick=\"$module(\u0027_FLAKE_ID_\u0027).editEdit()\" class=\"button\"/\u003e&nbsp;&nbsp;\u003cinput type=\"button\" onclick=\"$module(\u0027_FLAKE_ID_\u0027).toggleEdit()\" class=\"button cancel\" value=\"Cancel\"/\u003e\u003c/td\u003e\u003c/tr\u003e \u003c/table\u003e \u003c/div\u003e \u003c/div\u003e \u003c/div\u003e \u003cdiv class=\"flake_content\" style=\"_FLAKE_COLLAPSED_\" id=\"body_FLAKE_ID_\"\u003e \u003cdiv class=\"flake_spaceholder\"\u003eLoading...\u003c/div\u003e \u003c/div\u003e \u003cdiv class=\"flake_footer\"\u003e\u003ca id=\"collapseLink_FLAKE_ID_\" title=\"Collapse Flake\" class=\"colapse_icon\" onmouseover=\"hover(this)\" onmouseout=\"hout(this)\" style=\"_FLAKE_COLLAPSED_\" onclick=\"$module(\u0027_FLAKE_ID_\u0027).collapse()\"\u003e-\u003c/a\u003e \u003ca id=\"expandLink_FLAKE_ID_\" class=\"expand_icon\" title=\"Expand Flake\" style=\"_FLAKE_EXPANDED_\" onmouseover=\"hover(this)\" onmouseout=\"hout(this)\" onclick=\"$module(\u0027_FLAKE_ID_\u0027).expand()\"\u003e+\u003c/a\u003e\u003c/div\u003e \u003c/div\u003e\u003c/div\u003e"
            , "StylesheetHref": "http://www.pageflakes.com/App_Themes/T12/s.axd?s=CSS1&h=www.pageflakes.com&l=en&v=&b=Mozilla&m=5&t=T12"
            , "PopupHtml": "\u003cdiv class=\"flake_placeholder\"\u003e\u003cdiv class=\"flake\"\u003e\u003cdiv class=\"flake_header\" id=\"handle_FLAKE_ID_\" onmouseover=\"opqTb(this)\" onmouseout=\"alphaTb(this)\"\u003e\u003cdiv class=\"flake_toolbar\"\u003e\u003cdiv class=\"close_icon\" id=\"closeLink_FLAKE_ID_\" onmouseover=\"hover(this)\" onmouseout=\"hout(this)\"\u003ex\u003c/div\u003e\u003c/div\u003e\u003cdiv class=\"flake_title\"\u003e\u003cspan class=\"flake_icon\"\u003e\u003cimg src=\"images/pficon.gif\" id=\"icon_FLAKE_ID_\" /\u003e\u003c/span\u003e\u003cspan class=\"flake_name flake_name_popup\" id=\"title_FLAKE_ID_\"\u003e_FLAKE_TITLE_\u003c/span\u003e\u003c/div\u003e\u003c/div\u003e\u003cdiv class=\"popup_content\" id=\"body_FLAKE_ID_\"\u003eLoading...\u003c/div\u003e\u003cdiv class=\"flake_footer\"\u003e\u003c/div\u003e\u003c/div\u003e\u003c/div\u003e"
            ,"ThemePath": "http://www.pageflakes.com/App_Themes/T12/"
    }, "CurrentPageTheme": { "__type": "Pageflakes.ObjectModel.PageTheme2, PageFlakes.ObjectModel", "IsCustomTheme": false, "ThemeName": "Cool Blue", "CanEdit": false, "CanDelete": false, "ThemeID": 12, "VersionNo": 4, "CSS": ".menu * {\r\ncolor:#ffffff;\r\nfont:#ffffff;\r\n}\r\n\r\n.menu a {\r\ncolor:#ffffff;\r\nfloat:left;\r\nfont-weight:bold;\r\ntext-decoration:none;\r\n}", "PreviewGraphics": "App_Themes/Purple_Unified/ThemePreview.png", "Properties": {}, "ThemeHandlerUrl": "/p.axd?i=12&t=&h=www.pageflakes.com&v=4&b=AppleMAC-Safari&m=5", "ThemeShortcut": "T12", "PreviewHandlerUrl": "App_Themes/Purple_Unified/ThemePreview.png" },
    "Pages": [{ "__type": "Pageflakes.ObjectModel.PageSetting, PageFlakes.ObjectModel",
        "ID": 25509228,
        "VersionNo": 78,
        "Name": "Essais des pages",
        "OrderNo": 1,
        "SharingStatus": 0,
        "ColumnCount": 4,
        "OwnerName": "franckMdeRomans",
        "OwnerFullname": "Franck",
        "HitCount": 0,
        "IsPublished": false,
        "IsOwner": true,
        "IsShared": false,
        "Modules": null,
        "PageParts": null,
        "Scripts": null,
        "Stylesheets": null,
        "CanMoveFlakes": true,
        "CanAddFlake": true,
        "CanEditFlake": true,
        "CanDeleteFlake": true,
        "CanChangeFlake": true, "CanRemovePage": true, "CanChangePage": true, "CanInviteOthers": true, "IsNewlyShared": false, "SharedBy": "",
        "HasChanged": false, "ColumnSizes": "25%,25%,25%,25%",
        "Theme": { "__type": "Pageflakes.ObjectModel.PageTheme2, PageFlakes.ObjectModel", "IsCustomTheme": false, "ThemeName": "Shoes", "CanEdit": false, "CanDelete": false, "ThemeID": 386, "VersionNo": 3, "CSS": "\t\tbody\r\n\t\t{\r\n\t\t\r\n\t\t\t\tbackground: url(\u0027__IMG_PATH__ImageFile.ashx?eco_storageId=18705\u0027);\r\n\t\t\t\tbackground-color: none;\r\n\t\t\t\r\n\t\t}\r\n\r\n\t\t\r\n\t\t #header\r\n\t\t{\r\n\t\t\t\r\n\t\t\t\t\tbackground: url(\u0027__IMG_PATH__ImageFile.ashx?eco_storageId=18704\u0027);\r\n\t\t\t\t\r\n\t\t}\r\n\t\t\r\n\t\t\r\n\t\t\t .flake_placeholder\r\n\t\t\t{\r\n\t\t\tbackground-color: transparent\r\n\t\t\t}\r\n\t\t\r\n\t\t\t\t#Start{background-image:none;\r\n\t\t\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__IMG_PATH__images/themes/startbuttons/4.png\", sizingMethod=\"crop\");}\r\n\r\n\t\t\t\thtml\u003ebody  #Start{background-image:url(\u0027__IMG_PATH__images/themes/startbuttons/4.png\u0027);}\r\n\t\t\t\t\r\n\t\t\t\t\t\t#header .Start_down{background-image:none;\r\n\t\t\t\t\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__IMG_PATH__images/themes/startbuttons/4_down.png\", sizingMethod=\"crop\");}\r\n\r\n\t\t\t\t\t\thtml\u003ebody  #header .Start_down{background-image:url(\u0027__IMG_PATH__images/themes/startbuttons/4_down.png\u0027);}\r\n\t\t\t\t\t\r\n\t\t\t\t/* else #19AF05 */\r\n\t\t\t\t.flake_header\r\n\t\t\t\t{\r\n\t\t\t\t\tbackground: url(\u0027__IMG_PATH__Brush.ashx?w=20&h=30&t=g&a=90&p=40&m=FLD&c=19AF05\u0027) repeat-x;\r\n\t\t\t\t}\r\n\t\t\t\t.flake_footer\r\n\t\t\t\t{\r\n\t\t\t\tbackground: url(\u0027__IMG_PATH__Brush.ashx?w=20&h=15&t=g&a=90&p=40&m=FLD&c=19AF05\u0027) repeat-x;\r\n\t\t\t\t}\r\n\t\t\t\t\r\n\t\t\t\t .flake { border-color: transparent }\r\n\t\t\t\r\n\t\t\t\t .flake_name { color: #F0F0F0 }\r\n\t\t\t\r\n\t\t\t\t .footer_wrapper {background: url(__APP_THEMES__Standard/footer_trick.gif) top left repeat-x;}\r\n\t\t\t\r\n\t\t\t\t .language {background-color: white;top:0px;}\r\n\t\t\t\r\n\t\t #gray_panel { background: #DDDDDE none; }\r\n\t\t\r\n\t\t\t.page_tab\r\n\t\t\t{\r\n\t\t\tbackground-color: #19AF05;\r\n      background-image: none;\r\n      }\r\n      #gray_panel { background-color: #19AF05;color: #F0F0F0; }\r\n      #pagecast_invite_panel { background-color: #19AF05;color: #F0F0F0; }\r\n      #quick_invite_bar { background-color: #19AF05;color: #F0F0F0; }\r\n      #pIImportAddress { color: #F0F0F0; }\r\n    \r\n\t\t\t.page_tab .page_title { color: #F0F0F0 }\r\n\t\t\r\n\t\t\t .page_tab_off\r\n\t\t\t{\r\n\t\t\tbackground-color: #323232;\r\n\t\t\tbackground-image: none;\r\n\t\t\t}\r\n\t\t\r\n\t\t\t .page_tab_off .page_title { color: #F0F0F0 }\r\n\t\t\r\n\r\n\t\t\t\t .logo{\r\n\t\t\t\tbackground-image:none;\r\n\t\t\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__APP_THEMES__common/Pageflakes-Logo.png\", sizingMethod=\"crop\");\r\n\t\t\t\t}\r\n\r\n\t\t\t\thtml\u003ebody  .logo{background-image:url(\u0027__APP_THEMES__common/Pageflakes-Logo.png\u0027);}\r\n\r\n\t\t\t\r\n\t\t\r\n\r\n\r\n\t\t .errorIcon{ background:url(__APP_THEMES__Standard/error.gif) no-repeat top left; }\r\n\t\t #left_scroll { background: url(__APP_THEMES__Standard/scroll_left.png) no-repeat; }\r\n\t\t #right_scroll { background: url(__APP_THEMES__Standard/scroll_right.png) no-repeat; }\r\n\r\n\t\t .settings { background: #d1d1d1 url(__APP_THEMES__Standard/settings_bg.gif) 100% 100% no-repeat; }\r\n\t\t .link_to_gallery {background: no-repeat url(__APP_THEMES__Standard/link_to_gallery.gif) 100%; }\r\n\t\t #searchFormInputContainer { background:url(\u0027__APP_THEMES__common/Search-Box.gif\u0027) no-repeat; }\r\n\t\thtml\u003ebody  #searchFormInputContainer { background:url(\u0027__APP_THEMES__common/Search-Box.png\u0027) no-repeat; }\r\n\t\t .searchFormButtonBG { background:url(\u0027__APP_THEMES__Standard/Search-Arrow.png\u0027) no-repeat; }\r\n\t\t #searchEngine_selector { background:url(\u0027__APP_THEMES__Standard/down_arrow.gif\u0027) no-repeat; }\r\n\r\n\t\t .flake_content_with_shadow { background: #FFF url(\"__APP_THEMES__Standard/bg.gif\") repeat-x bottom; }\r\n\t\t .flake_settings{ background: #d1d1d1 url(__APP_THEMES__Standard/settings_bg.gif) 100% 100% no-repeat; }\r\n\r\n\t\t #gray_panel_table a { background: url(__APP_THEMES__Standard/rss.gif) no-repeat 3px 50%; }\r\n\r\n\t\t .logo_box{ background: url(__APP_THEMES__Standard/123_logo_bg.gif) }\r\n\t\t .page_close  { background:transparent url(__APP_THEMES__Standard/page_close.gif) no-repeat scroll left top; }\r\n\t\t .hide_page_settings{ background:url(__APP_THEMES__Standard/page_settings_arrow_up.gif) 0 2px no-repeat; }\r\n\t\t .refresh_icon{ background:url(__APP_THEMES__Standard/refresh.gif) 1px 1px no-repeat; }\r\n\t\t .refresh_icon_hover { background:#fff url(__APP_THEMES__Standard/refresh.gif) top left no-repeat; }\r\n\r\n\t\t .alerts { background-color: #8283C4; }\r\n\r\n\t\t/* RSS Reader styles */\r\n\t\t .feedViewer_channelSelected{ height:25px; line-height:25px; padding-left:1px;background:#CACACA;cursor:pointer;cursor:hand;margin:0px;-moz-user-select: none;-khtml-user-select: none;user-select: none;}\r\n\t\t .feedViewer_channelNotSelected{ height:25px; line-height:25px; padding-left:1px;background:none;cursor:pointer;cursor:hand;margin:0px;-moz-user-select: none;-khtml-user-select: none;user-select: none;}\r\n\r\n\t\t .feedViewer_allSelected{height:25px; padding-left:1px;line-height:25px; background:#DDDDDD;-moz-user-select: none;-khtml-user-select: none;user-select: none;}\r\n\t\t .feedViewer_allNotSelected{height:25px; padding-left:1px;line-height:25px; background:none;-moz-user-select: none;-khtml-user-select: none;user-select: none;}\r\n\t\t .feedViewer_channelMouseOver{}\r\n\r\n\t\t #PageflakesTV{background-image:none;\r\n\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__APP_THEMES__Standard/PageflakesTV.png\", sizingMethod=\"crop\");}\r\n\r\n\t\thtml\u003ebody  #PageflakesTV{background-image:url(\u0027__APP_THEMES__Standard/PageflakesTV.png\u0027);}\r\n\r\n\t\t #right_scroll{background-image:none;\r\n\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__APP_THEMES__Standard/scroll_right.png\", sizingMethod=\"crop\");}\r\n\r\n\t\thtml\u003ebody  #right_scroll{background-image:url(\u0027__APP_THEMES__Standard/scroll_right.png\u0027);}\r\n\r\n\t\t #left_scroll{background-image:none;\r\n\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__APP_THEMES__Standard/scroll_left.png\", sizingMethod=\"crop\");}\r\n\r\n\t\thtml\u003ebody  #left_scroll{background-image:url(\u0027__APP_THEMES__Standard/scroll_left.png\u0027);}\r\n\r\n\t\t/* #searchEngine_selector{background-image:none;\r\n\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__APP_THEMES__Standard/searchDown.png\", sizingMethod=\"crop\");}\r\n\r\n\t\thtml\u003ebody  #searchEngine_selector{background-image:url(\u0027__APP_THEMES__Standard/searchDown.png\u0027);}*/\r\n\r\n\t\t", "PreviewGraphics": "ImageFile.ashx?eco_storageId=18800", "Properties": {}, "ThemeHandlerUrl": "/p.axd?i=386&t=&h=www.pageflakes.com&v=3&b=AppleMAC-Safari&m=5", "ThemeShortcut": "T386", "PreviewHandlerUrl": "ImageFile.ashx?eco_storageId=18800"}
    },
    { "__type": "Pageflakes.ObjectModel.PageSetting, PageFlakes.ObjectModel",
        "ID": 32864156,
        "VersionNo": 18,
        "Name": "My New Page",
        "OrderNo": 1,
        "SharingStatus": 1,
        "ColumnCount": 3,
        "OwnerName": "franckMdeRomans",
        "OwnerFullname": "Franck",
        "HitCount": 0,
        "IsPublished": true,
        "IsOwner": true,
        "IsShared": false,
        "Modules": null,
        "PageParts": null,
        "Scripts": null,
        "Stylesheets": null,
        "CanMoveFlakes": true,
        "CanAddFlake": true,
        "CanEditFlake": true,
        "CanDeleteFlake": true,
        "CanChangeFlake": true,
        "CanRemovePage": true,
        "CanChangePage": true,
        "CanInviteOthers": true,
        "IsNewlyShared": false,
        "SharedBy": "",
        "HasChanged": false,
        "ColumnSizes": "33%,33%,33%",
        "Theme": { "__type": "Pageflakes.ObjectModel.PageTheme2, PageFlakes.ObjectModel", "IsCustomTheme": false, "ThemeName": "Zune", "CanEdit": false, "CanDelete": false, "ThemeID": 564, "VersionNo": 1, "CSS": "\t\tbody\r\n\t\t{\r\n\t\t\r\n\t\t\t\tbackground-color: #ccc5b2;\r\n\t\t\t\tbackground-image: none;\r\n\t\t\t\r\n\t\t}\r\n\r\n\t\t\r\n\t\t #header\r\n\t\t{\r\n\t\t\t\r\n\t\t\t\t\tbackground: url(\u0027__IMG_PATH__ImageFile.ashx?eco_storageId=28757\u0027);\r\n\t\t\t\t\r\n\t\t}\r\n\t\t\r\n\t\t\r\n\t\t\t .flake_placeholder\r\n\t\t\t{\r\n\t\t\tbackground-color: #f78c23\r\n\t\t\t}\r\n\t\t\r\n\t\t\t\t#Start{background-image:none;\r\n\t\t\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__IMG_PATH__images/themes/startbuttons/5.png\", sizingMethod=\"crop\");}\r\n\r\n\t\t\t\thtml\u003ebody  #Start{background-image:url(\u0027__IMG_PATH__images/themes/startbuttons/5.png\u0027);}\r\n\t\t\t\t\r\n\t\t\t\t\t\t#header .Start_down{background-image:none;\r\n\t\t\t\t\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__IMG_PATH__images/themes/startbuttons/5_down.png\", sizingMethod=\"crop\");}\r\n\r\n\t\t\t\t\t\thtml\u003ebody  #header .Start_down{background-image:url(\u0027__IMG_PATH__images/themes/startbuttons/5_down.png\u0027);}\r\n\t\t\t\t\t\r\n\t\t\t\t/* else #ccc5b2 */\r\n\t\t\t\t.flake_header\r\n\t\t\t\t{\r\n\t\t\t\t\tbackground: url(\u0027__IMG_PATH__Brush.ashx?w=20&h=30&t=g&a=90&p=40&m=FLD&c=ccc5b2\u0027) repeat-x;\r\n\t\t\t\t}\r\n\t\t\t\t.flake_footer\r\n\t\t\t\t{\r\n\t\t\t\tbackground: url(\u0027__IMG_PATH__Brush.ashx?w=20&h=15&t=g&a=90&p=40&m=FLD&c=ccc5b2\u0027) repeat-x;\r\n\t\t\t\t}\r\n\t\t\t\t\r\n\t\t\t\t .flake { border-color: #ed0d89 }\r\n\t\t\t\r\n\t\t\t\t .flake_name { color: #4B423A }\r\n\t\t\t\r\n\t\t\t\t .footer_block * { color: #ccc5b2 }\r\n\t\t\t\t .footer_block:hover { color: #ccc5b2 }\r\n\t\t\t\t .footer_block ul li a:visited{ color: #ccc5b2 }\r\n\t\t\t\t .footer_block ul li a:hover{ color: #ccc5b2 }\r\n\t\t\t\t .footer_block ul li a{ color: #ccc5b2 }\r\n\t\t\t\t .footer_block:hover a{ color: #ccc5b2 }\r\n\t\t\t\r\n\t\t\t\t .footer_wrapper {background-color: #726551}\r\n\t\t\t\r\n\t\t\t\t #TopMenu *{color: #ed0d89}\r\n\t\t\t\r\n\t\t\t\t #TopMenu li#UserFullName #homeProfileLink{color: #FFFFFF}\r\n\t\t\t\r\n\t\t\t\t.language {/*top:-7px;margin-bottom:-7px;*/}\r\n\t\t\t\r\n\t\t #gray_panel { background: #DDDDDE none; }\r\n\t\t\r\n\t\t\t.page_tab\r\n\t\t\t{\r\n\t\t\tbackground-color: #ed0d89;\r\n      background-image: none;\r\n      }\r\n      #gray_panel { background-color: #ed0d89;color: #FFFFFF; }\r\n      #pagecast_invite_panel { background-color: #ed0d89;color: #FFFFFF; }\r\n      #quick_invite_bar { background-color: #ed0d89;color: #FFFFFF; }\r\n      #pIImportAddress { color: #FFFFFF; }\r\n    \r\n\t\t\t.page_tab .page_title { color: #FFFFFF }\r\n\t\t\r\n\t\t\t .page_tab_off\r\n\t\t\t{\r\n\t\t\tbackground-color: #FFFFFF;\r\n\t\t\tbackground-image: none;\r\n\t\t\t}\r\n\t\t\r\n\t\t\t .page_tab_off .page_title { color: #f78c23 }\r\n\t\t\r\n\r\n\t\t\t\t .logo{\r\n\t\t\t\tbackground-image:none;\r\n\t\t\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__APP_THEMES__common/Pageflakes-Logo.png\", sizingMethod=\"crop\");\r\n\t\t\t\t}\r\n\r\n\t\t\t\thtml\u003ebody  .logo{background-image:url(\u0027__APP_THEMES__common/Pageflakes-Logo.png\u0027);}\r\n\r\n\t\t\t\r\n\t\t\r\n\r\n\r\n\t\t .errorIcon{ background:url(__APP_THEMES__Standard/error.gif) no-repeat top left; }\r\n\t\t #left_scroll { background: url(__APP_THEMES__Standard/scroll_left.png) no-repeat; }\r\n\t\t #right_scroll { background: url(__APP_THEMES__Standard/scroll_right.png) no-repeat; }\r\n\r\n\t\t .settings { background: #d1d1d1 url(__APP_THEMES__Standard/settings_bg.gif) 100% 100% no-repeat; }\r\n\t\t .link_to_gallery {background: no-repeat url(__APP_THEMES__Standard/link_to_gallery.gif) 100%; }\r\n\t\t #searchFormInputContainer { background:url(\u0027__APP_THEMES__common/Search-Box.gif\u0027) no-repeat; }\r\n\t\thtml\u003ebody  #searchFormInputContainer { background:url(\u0027__APP_THEMES__common/Search-Box.png\u0027) no-repeat; }\r\n\t\t .searchFormButtonBG { background:url(\u0027__APP_THEMES__Standard/Search-Arrow.png\u0027) no-repeat; }\r\n\t\t #searchEngine_selector { background:url(\u0027__APP_THEMES__Standard/down_arrow.gif\u0027) no-repeat; }\r\n\r\n\t\t .flake_content_with_shadow { background: #FFF url(\"__APP_THEMES__Standard/bg.gif\") repeat-x bottom; }\r\n\t\t .flake_settings{ background: #d1d1d1 url(__APP_THEMES__Standard/settings_bg.gif) 100% 100% no-repeat; }\r\n\r\n\t\t #gray_panel_table a { background: url(__APP_THEMES__Standard/rss.gif) no-repeat 3px 50%; }\r\n\r\n\t\t .logo_box{ background: url(__APP_THEMES__Standard/123_logo_bg.gif) }\r\n\t\t .page_close  { background:transparent url(__APP_THEMES__Standard/page_close.gif) no-repeat scroll left top; }\r\n\t\t .hide_page_settings{ background:url(__APP_THEMES__Standard/page_settings_arrow_up.gif) 0 2px no-repeat; }\r\n\t\t .refresh_icon{ background:url(__APP_THEMES__Standard/refresh.gif) 1px 1px no-repeat; }\r\n\t\t .refresh_icon_hover { background:#fff url(__APP_THEMES__Standard/refresh.gif) top left no-repeat; }\r\n\r\n\t\t .alerts { background-color: #8283C4; }\r\n\r\n\t\t/* RSS Reader styles */\r\n\t\t .feedViewer_channelSelected{ height:25px; line-height:25px; padding-left:1px;background:#CACACA;cursor:pointer;cursor:hand;margin:0px;-moz-user-select: none;-khtml-user-select: none;user-select: none;}\r\n\t\t .feedViewer_channelNotSelected{ height:25px; line-height:25px; padding-left:1px;background:none;cursor:pointer;cursor:hand;margin:0px;-moz-user-select: none;-khtml-user-select: none;user-select: none;}\r\n\r\n\t\t .feedViewer_allSelected{height:25px; padding-left:1px;line-height:25px; background:#DDDDDD;-moz-user-select: none;-khtml-user-select: none;user-select: none;}\r\n\t\t .feedViewer_allNotSelected{height:25px; padding-left:1px;line-height:25px; background:none;-moz-user-select: none;-khtml-user-select: none;user-select: none;}\r\n\t\t .feedViewer_channelMouseOver{}\r\n\r\n\t\t #PageflakesTV{background-image:none;\r\n\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__APP_THEMES__Standard/PageflakesTV.png\", sizingMethod=\"crop\");}\r\n\r\n\t\thtml\u003ebody  #PageflakesTV{background-image:url(\u0027__APP_THEMES__Standard/PageflakesTV.png\u0027);}\r\n\r\n    #right_scroll{background-image:none;\r\n    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__APP_THEMES__Standard/scroll_right.png\", sizingMethod=\"crop\");}\r\n\r\n    html\u003ebody  #right_scroll{background-image:url(\u0027__APP_THEMES__Standard/scroll_right.png\u0027);}\r\n\r\n\t\t #left_scroll{background-image:none;\r\n\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__APP_THEMES__Standard/scroll_left.png\", sizingMethod=\"crop\");}\r\n\r\n\t\thtml\u003ebody  #left_scroll{background-image:url(\u0027__APP_THEMES__Standard/scroll_left.png\u0027);}\r\n\r\n\t\t/* #searchEngine_selector{background-image:none;\r\n\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"__APP_THEMES__Standard/searchDown.png\", sizingMethod=\"crop\");}\r\n\r\n\t\thtml\u003ebody  #searchEngine_selector{background-image:url(\u0027__APP_THEMES__Standard/searchDown.png\u0027);}*/\r\n\r\n\t\t.footer_wrapper a:link {\r\ncolor: #ccc5b2;\r\nfont-weight: bold;\r\n}\r\n\r\n#gray_panel {\r\nbackground-color: #ed0d89;\r\nbackground-image: url(http://270studios.com/PageFlakes/graypanelZUNE.jpg);\r\nbackground-repeat: no-repeat;\r\n}\r\n\r\n.footer_wrapper {\r\ncolor: #4b423a;\r\n}\r\n\r\n .logo{\r\n\t\t\t\tbackground-image:none;\r\n\t\t\t\tfilter: progid:DXImageTransform.Microsoft.AlphaImageLoader (src=\"http://270studios.com/PageFlakes/logos/pageflakesZUNE.png\", sizingMethod=\"crop\");\r\n\t\t\t\t}\r\n\r\n\t\t\t\thtml\u003ebody  .logo{background-image:url(\u0027http://270studios.com/PageFlakes/logos/pageflakesZUNE.png\u0027);}\r\n\r\n\r\n.flake_header {\r\nborder-bottom: 1px solid #ed0d89;\r\ntext-transform: uppercase;}\r\n\r\n.page_tab {\r\nfont-weight: bold;\r\n\r\n}\r\n\r\n\r\n.page_tab:hover {\r\nfont-weight: bold;\r\ntext-transform: uppercase;\r\n}\r\n.page_tab_off {\r\nfont-style: italic;\r\nfont-size: 10px;\r\n}\r\n\r\n.page_tab_off:hover {\r\nfont-style: italic;\r\ntext-transform: uppercase;\r\nfont-size: 10px;\r\n}", "PreviewGraphics": "ImageFile.ashx?eco_storageId=28764", "Properties": {}, "ThemeHandlerUrl": "/p.axd?i=564&t=&h=www.pageflakes.com&v=1&b=AppleMAC-Safari&m=5", "ThemeShortcut": "T564", "PreviewHandlerUrl": "ImageFile.ashx?eco_storageId=28764"}
    },
   { "__type": "Pageflakes.ObjectModel.PageSetting, PageFlakes.ObjectModel",
       "ID": 33874337,
       "VersionNo": 0,
       "Name": "My New Page",
       "OrderNo": 1,
       "SharingStatus": 0,
       "ColumnCount": 3,
       "OwnerName": "franckMdeRomans",
       "OwnerFullname": "Franck",
       "HitCount": 0,
       "IsPublished": false,
       "IsOwner": true,
       "IsShared": false,
       "Modules": null,
       "PageParts": null,
       "Scripts": null,
       "Stylesheets": null,
       "CanMoveFlakes": true,
       "CanAddFlake": true,
       "CanEditFlake": true,
       "CanDeleteFlake": true,
       "CanChangeFlake": true,
       "CanRemovePage": true,
       "CanChangePage": true,
       "CanInviteOthers": true,
       "IsNewlyShared": false,
       "SharedBy": "",
       "HasChanged": false,
       "ColumnSizes": "33%,33%,33%",
       "Theme": { "__type": "Pageflakes.ObjectModel.PageTheme2, PageFlakes.ObjectModel", "IsCustomTheme": false, "ThemeName": "Cool Blue", "CanEdit": false, "CanDelete": false, "ThemeID": 12, "VersionNo": 4, "CSS": ".menu * {\r\ncolor:#ffffff;\r\nfont:#ffffff;\r\n}\r\n\r\n.menu a {\r\ncolor:#ffffff;\r\nfloat:left;\r\nfont-weight:bold;\r\ntext-decoration:none;\r\n}", "PreviewGraphics": "App_Themes/Purple_Unified/ThemePreview.png", "Properties": {}, "ThemeHandlerUrl": "/p.axd?i=12&t=&h=www.pageflakes.com&v=4&b=AppleMAC-Safari&m=5", "ThemeShortcut": "T12", "PreviewHandlerUrl": "App_Themes/Purple_Unified/ThemePreview.png"}
   },
    { "__type": "Pageflakes.ObjectModel.PageSetting, PageFlakes.ObjectModel",
        "ID": 33874442,
        "VersionNo": 9,
        "Name": "My New Page",
        "OrderNo": 1,
        "SharingStatus": 0,
        "ColumnCount": 3,
        "OwnerName": "franckMdeRomans",
        "OwnerFullname": "Franck",
        "HitCount": 0,
        "IsPublished": false,
        "IsOwner": true,
        "IsShared": false,
        "Modules": [{ "__type": "Pageflakes.ObjectModel.Module, PageFlakes.ObjectModel",
            "id": "m313466497",
            "row": 0,
            "col": 1,
            "title": "Weather Channel",
            "url": "__WEATHERCOMFLAKE__",
            "internalID": 313466497,
            "pageID": 33874442,
            "expanded": true,
            "Permission": { "__type": "Pageflakes.ObjectModel.Permission, PageFlakes.ObjectModel", "CanDrag": true, "CanEdit": true, "CanCollapse": true, "CanClose": true },
            "Profiles": { "UNIT": "m", "TABSELECT": "0", "SHOWCITIES": "tabs", "OPENLINKS": "new", "LOCID": "", "LOCNAME": "", "LOCCHK": "0" },
            "PrivateProfiles": {},
            "ProtectedProfiles": {},
            "PublicProfiles": {}
        },
        { "__type": "Pageflakes.ObjectModel.Module, PageFlakes.ObjectModel",
            "id": "m313466442",
            "row": 1,
            "col": 1,
            "title": "Anything Flake2",
            "url": "__HTML_FLAKE__",
            "internalID": 313466442,
            "pageID": 33874442,
            "expanded": true,
            "Permission": { "__type": "Pageflakes.ObjectModel.Permission, PageFlakes.ObjectModel", "CanDrag": true, "CanEdit": true, "CanCollapse": true, "CanClose": true },
            "Profiles": { "id": "2044578", "title": "Anything Flake2", "Icon": "", "BORDER": "T" },
            "PrivateProfiles": {},
            "ProtectedProfiles": {},
            "PublicProfiles": {}
        }],
        "PageParts": [{ "__type": "Pageflakes.ObjectModel.PageParts, PageFlakes.ObjectModel",
            "scripts": [{ "__type": "Pageflakes.ObjectModel.ScriptTag, PageFlakes.ObjectModel",
                "id": "CommonFlakeJS_TopFlakes",
                "src": "/f.axd?s=CommonFlakeJS_TopFlakes&t=j&v=217",
                "content": null
            },
            { "__type": "Pageflakes.ObjectModel.ScriptTag, PageFlakes.ObjectModel",
                "id": "m313466497Instance",
                "src": null,
                "content": "\n$m313466497=function(){return new WeatherComFlake(\u0027m313466497\u0027);}"
            }],
            "styles": [{ "__type": "Pageflakes.ObjectModel.StyleTag, PageFlakes.ObjectModel", "id": "CommonFlakeCSS", "href": "/f.axd?s=CommonFlakeCSS&t=c&v=217",
                "content": null
            }],
            "body": "",
            "id": "m313466497",
            "title": "The Weather Channel&amp;reg;",
            "url": "flakes/WeatherComFlake/Weather.html",
            "icon": "images/pficon.gif",
            "importUrl": null,
            "exportUrl": null,
            "xslUrl": null,
            "Permission": { "__type": "Pageflakes.ObjectModel.Permission, PageFlakes.ObjectModel", "CanDrag": true, "CanEdit": true, "CanCollapse": true, "CanClose": true },
            "texts": {}
        },
        { "__type": "Pageflakes.ObjectModel.PageParts, PageFlakes.ObjectModel", "scripts": [{ "__type": "Pageflakes.ObjectModel.ScriptTag, PageFlakes.ObjectModel", "id": "PopupWindow_Script", "src": "/flakes/CustomeFlake/PopupWindow.js", "content": null }, { "__type": "Pageflakes.ObjectModel.ScriptTag, PageFlakes.ObjectModel", "id": "CustomeFlakeEditor_Script", "src": "/flakes/CustomeFlake/CustomeFlakeEditor.js?v=1", "content": null }, { "__type": "Pageflakes.ObjectModel.ScriptTag, PageFlakes.ObjectModel", "id": "m313466442Instance", "src": null, "content": "\n$m313466442=function(){return new CustomeFlakeEditor(\u0027m313466442\u0027);}"}], "styles": [], "body": "", "id": "m313466442", "title": "Anything Flake", "url": "flakes/CustomeFlake/CustomeFlakeEditor.html", "icon": "images/pficon.gif", "importUrl": "http://localhost/flakes/Customeflake/CustomeFlakeService.asmx/Import", "exportUrl": "http://localhost/flakes/Customeflake/CustomeFlakeService.asmx/Export", "xslUrl": null, "Permission": { "__type": "Pageflakes.ObjectModel.Permission, PageFlakes.ObjectModel", "CanDrag": true, "CanEdit": true, "CanCollapse": true, "CanClose": true }, "texts": {}}],
        "Scripts": null, "Stylesheets": null,
        "CanMoveFlakes": true, "CanAddFlake": true, "CanEditFlake": true, "CanDeleteFlake": true, "CanChangeFlake": true, "CanRemovePage": true,
        "CanChangePage": true, "CanInviteOthers": true, "IsNewlyShared": false, "SharedBy": "",
        "HasChanged": false, "ColumnSizes": "33%,33%,33%",
        "Theme": { "__type": "Pageflakes.ObjectModel.PageTheme2, PageFlakes.ObjectModel", "IsCustomTheme": false, "ThemeName": "Cool Blue", "CanEdit": false, "CanDelete": false, "ThemeID": 12, "VersionNo": 4, "CSS": ".menu * {\r\ncolor:#ffffff;\r\nfont:#ffffff;\r\n}\r\n\r\n.menu a {\r\ncolor:#ffffff;\r\nfloat:left;\r\nfont-weight:bold;\r\ntext-decoration:none;\r\n}", "PreviewGraphics": "App_Themes/Purple_Unified/ThemePreview.png", "Properties": {}, "ThemeHandlerUrl": "/p.axd?i=12&t=&h=www.pageflakes.com&v=4&b=AppleMAC-Safari&m=5", "ThemeShortcut": "T12", "PreviewHandlerUrl": "App_Themes/Purple_Unified/ThemePreview.png"}
    }],
    "SearchEngine": 0,
    "ShowSearchBar": true, "IsAnonymous": false, "IsMySite": true, "PageSharedWithMeCount": 0,
    "Channels": null, "IsFirstVisit": false,
    "ShowWelcomeWizard": false,
    "ErrorMsg": "",
    "My": { "__type": "Pageflakes.ObjectModel.UserMetadata, PageFlakes.ObjectModel",
        "UniqueName": "franckMdeRomans",
        "Interests": ["everythings"],
        "SpecificInterests": "",
        "Country": "France",
        "State": "",
        "City": "Valence",
        "Timezone": 100,
        "ZipCode": "",
        "Profile": { "BVSTT": "1", "Language": "en", "WelcomeWizardCompleted": "True", "IsRealUser": "True", "MSHP": "1", "MSUI": "0", "UV": "19", "MLSV": "0",
            "CurrentPageID": "33874442",
            "PageOrder": "25509228,32864156,33874337,33874442"
        },
        "FirstName": "Franck",
        "LastName": "Marquis",
        "InProductMessage": "homepage|\u003cstrong\u003eTip: \u003ca class=\"InProductLink\" id=\"SetHomePageLink\" href=\"javascript:void(0);\" onclick=\"StartPageHelper.setAsStartPage(this, true);\" title=\"Make Pageflakes your home page\" \u003e\u003cu\u003eMake Pageflakes your home page!\u003c/u\u003e\u003c/a\u003e\u003c/strong\u003e "
    },
    "IsCurrentPageLoaded": true
})
    window.__preCachedRSS = null
})();