var Lang=
{
SAVE:"Save",
CANCEL:"Cancel",
SAVING:"Saving...",
EDIT:"Edit",
END_EDIT:"End Edit",
NO_BOOKMARKS:"You have no bookmarks.",
PUBLIC_PAGE_MESSAGE__:"This is a public page and you cannot edit this page. It belongs to ",
SHARED_PAGE_MESSAGE__:"This is a shared page and you can edit this page. It belongs to ",
SHARED_PAGE_MESSAGE2__:"This is a shared page. It belongs to ",
EMAIL_COMMA:"Emails, separated by commas",
TAGS_COMMA:"Tags, separated by commas",
PUBLISH_SUCCESS:"Page template has been added at: <a href='{0}'>{0}</a>",
PUBLISH_FAILED:"Error occured while publishing the page. Please try again.",
SOMETHING_WRONG:"Something is wrong with your page. Please try refreshing the page. \n\nIf the problem still persists, please let us know via email: info@Pageflakes.com. \n\nWe are sorry for the inconvenience.",
NO_PAGE_TO_ViEW:"There is no page for you to see on this user's site. <"+"a href=\"Default.aspx\">Click here to go back to your pages<"+"/>",
COMMON_ERROR_ALERT:"There was a problem processing you request. Please retry your last action.",
COMMON_ERROR_MESSAGE:"There was a problem processing you request. Please retry. The actual error is: ",
NO_FEED_TO_VIEW:"No feed found at url: {0}",
SIGNUP_TO_SHARE:"Please <b><a href='PageflakesRegistration.aspx'>Sign-up</a></b> or <b><a href='Login.aspx'>login</a></b> to share this page with your friends.",
SIGNUP_TO_CHANGE:"Please <b><a href='PageflakesRegistration.aspx'>Sign-up</a></b> or <b><a href='Login.aspx'>login</a></b> to change these settings.",
BOOKMARKS:"Bookmarks",
PAGE_MADE_PRIVATE:"This page is now private. Only you can access it.",
PAGE_MADE_PUBLIC_AT:"This page is now public. Everyone can see it from: <a href='{0}'>{0}</a>. <br/>The page is also published in the community at: <a href='{1}'>{1}</a>",
PAGE_MADE_SHARED:"This page is now shared.",
ADD_FEED:'ADD FEED',
ADD_FLAKE:'ADD FLAKE',
ADD_PAGE:'ADD PAGE',
UNKNOWN:"Unknown",
SETTINGS:'Settings',
DOWNLOADING:"Downloading...",
SEND:"Send",
SENDING:"Sending...",
LOADING:"Loading...",
UNTITLED:"(untitled)",
NEW___:'New...',
MY_NEW_PAGE:"My New Page",
UNKNOWN_ERROR:"Unknown error",
SURE_REMOVE_:"Are you sure you want to remove: ",_NO_UNDO:". There is no undo and you will lose all your data",
CANT_DEL_LAST_PAGE:"Cannot delete the last page",
MODULE_NOT_LOADED:"Module not loaded properly from: ",
NO_PERM_ADD_FLAKE:"You do not have permission to add flake on this page",
_THE_OWNER_CAN_ADD:", the owner of the page, can edit this flake",
THIS_PAGE_:"This is a page ",_SHARED_WITH_YOU:" shared with you. You can view and edit it.",
THIS_PAGE_OF_:"This is a public page of ",_VIEW_NOT_EDIT:". You can view but not edit it",
LOGIN_TO_PUB:"Please log in or signup (free) to publish a page",
LOGIN_TO_SH:"Please log in or signup (free) to share a page",
DELETE_PAGE:"Delete the page:",AND_ALL_FLAKE:"and ALL its flakes along with all the data within them?",
PUB_SET:'Publishing Settings',
SH_SET:'Share Settings',
SH_TO_ME:'Pages shared with me',
CONFIRM_UNPUB:'Are you sure you want to un-publish this page?',
YES_UNPUB:'Yes - Make it private',
NO_KEEPPUB:'No - Keep it public',
CONF_UNSHARE:"Are you sure you want to un-share this page?",
CONF_UNINVITE:"Are you sure you want to un-invite this user?",
YES_MAKEPRIVATE:"Yes - Make it private",
USER_NOMORE:"Yes – user can no longer view this page",
NO_KEEPSHARE:"No - Keep it shared",
NO_USERCONTINUE:"No – let the user continue to view this page",
ONE_EMAIL:"Please enter at least one email address",
ONE_TAG:"Please enter at least one tag. e.g. Entertainment",
DESC_REQUIRED:"Please enter a description",
PERSONAL_MSG:"Personal Message:",
ENTER_VALID_ADDRESS:"Please enter valid email address",
MY_SAVED_ARTICLES:"My Saved Articles",
ALL_FEEDS:"ALL FEEDS",
SAVE_ARTICLE:"Save article",
DELETE_ARTICLE:"Delete article",
FORWARD_ARTICLE:"Forward article",
GOTO_SOURCE:"Go to source",
DELETE_ARTICLE_CONFIRM:"Would you like to delete this article from your saved list? (OK = Yes   Cancel = No)",
EMAIL_SUCCESS:"Email was sent successfully.",
EMAIL_FAILED:"Failed to send email.",
SOMEONE:"Someone",
LOAD_NEXT20ARTICLES:"Load <b>n</b>ext 20 articles",
LOAD_NEXT10ARTICLES:"Load <b>n</b>ext 10 articles",
LOAD_NEXT:"Load next",
ARTICLES:"Articles",
PUBLISHED_AT:"Published at",
NEXT:"Next",
PREVIOUS:"Previous",
NEXT2:"<b>N</b>ext",
PREVIOUS2:"<b>P</b>revious",
MARK_AS_READ:"Mark as Read",
MARK_AS_UNREAD:"Mark as Unread",
MARK_ALL_READ:"Mark all Read",
MARK_ALL_UNREAD:"Mark all Unread",
MARK:"Mark...",
MARK_ALL_ARTICLES_READ:"all articles read",
MARK_ALL_ARTICLES_UNREAD:"all articles unread",
SELECTED_ARTICLES_READ:"selected article read",
SELECTED_ARTICLES_UNREAD:"selected article unread",
RSS_FEED_FORWARD_EMAIL_TEMPLATE:"RssFeedForwardEmailTemplate",
RELOAD_AGAIN:"Could not load the site. Press 'OK' to try again.",
START_OVER:"Do you want to delete all the pages and start over again?",
YES_START_OVER:"Yes, delete all pages and start over",
NO_START_OVER:"No, keep my pages",
RSS_READER:"RSS READER"};
